/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-07-15 05:18:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>MovieZone - Book Tickets</title>\n");
      out.write("\n");
      out.write("  <!-- 🎨 Fonts -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Cinzel:wght@600&family=Open+Sans:wght@400;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      margin: 0;\n");
      out.write("      display: flex;\n");
      out.write("      height: 100vh;\n");
      out.write("      font-family: 'Open Sans', sans-serif;\n");
      out.write("      background: linear-gradient(120deg, #1f1c2c, #928dab);\n");
      out.write("      color: #fff;\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 🔘 Left Content Panel */\n");
      out.write("    .content {\n");
      out.write("      width: 50%;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      justify-content: center;\n");
      out.write("      align-items: center;\n");
      out.write("      padding: 40px;\n");
      out.write("      z-index: 2;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    h1 {\n");
      out.write("      font-family: 'Cinzel', serif;\n");
      out.write("      font-size: 3rem;\n");
      out.write("      margin-bottom: 30px;\n");
      out.write("      text-shadow: 2px 2px 6px rgba(0, 0, 0, 0.5);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    a.button {\n");
      out.write("      font-weight: 600;\n");
      out.write("      display: inline-block;\n");
      out.write("      padding: 14px 30px;\n");
      out.write("      margin: 15px;\n");
      out.write("      background: #ff6b6b;\n");
      out.write("      color: #fff;\n");
      out.write("      text-decoration: none;\n");
      out.write("      border-radius: 10px;\n");
      out.write("      transition: 0.3s ease;\n");
      out.write("      font-size: 1rem;\n");
      out.write("      box-shadow: 0 4px 12px rgba(0,0,0,0.3);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    a.button:hover {\n");
      out.write("      background: #ff3b3b;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 🎞️ Right Vertical Slider */\n");
      out.write("   /* 🎞️ Right Vertical Slider */\n");
      out.write(".slider-panel {\n");
      out.write("  width: 50%;\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: center;\n");
      out.write("  align-items: center;\n");
      out.write("  background: rgba(0, 0, 0, 0.15);\n");
      out.write("  overflow: hidden;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".vertical-slider-track {\n");
      out.write("  display: flex;\n");
      out.write("  flex-direction: column;\n");
      out.write("  animation: scroll-vertical 40s linear infinite;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ✅ Increased Width, Height and Premium Styling */\n");
      out.write(".vertical-slide {\n");
      out.write("  width: 320px; /* Increased width */\n");
      out.write("  height: 480px; /* Increased height */\n");
      out.write("  margin: 16px auto;\n");
      out.write("  border-radius: 18px;\n");
      out.write("  overflow: hidden;\n");
      out.write("  box-shadow: 0 8px 24px rgba(0,0,0,0.5);\n");
      out.write("  transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("  border: 2px solid #ffffff30;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".vertical-slide:hover {\n");
      out.write("  transform: scale(1.05);\n");
      out.write("  box-shadow: 0 12px 28px rgba(0,0,0,0.6);\n");
      out.write("  border-color: #ff6b6b;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".vertical-slide img {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  object-fit: cover;\n");
      out.write("  transition: filter 0.3s ease;\n");
      out.write("  filter: brightness(95%) contrast(105%);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".vertical-slide:hover img {\n");
      out.write("  filter: brightness(100%) contrast(110%);\n");
      out.write("}\n");
      out.write("\n");
      out.write("@keyframes scroll-vertical {\n");
      out.write("  0% { transform: translateY(0); }\n");
      out.write("  100% { transform: translateY(-50%); }\n");
      out.write("}\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Left: Register/Login -->\n");
      out.write("  <div class=\"content\">\n");
      out.write("    <h1>🎬 Welcome to MovieZone</h1>\n");
      out.write("    <a href=\"register.jsp\" class=\"button\">Register</a>\n");
      out.write("    <a href=\"login.jsp\" class=\"button\">Login</a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Right: Vertical Slider -->\n");
      out.write("  <div class=\"slider-panel\">\n");
      out.write("    <div class=\"vertical-slider-track\">\n");
      out.write("      <!-- Add movie posters -->\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./animal.jpeg\" alt=\"Animal\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./Tu_Jhoothi_Main_Makkaar_poster.jpeg\" alt=\"TJMM\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./barfi.jpeg\" alt=\"Barfi\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./Sanju.jpeg\" alt=\"Sanju\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./ye_jawani_hai_diwani.jpeg\" alt=\"YJHD\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./rockstar.jpeg\" alt=\"Rockstar\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./Brahmastra_Part_One.jpeg\" alt=\"Brahmastra\"></div>\n");
      out.write("\n");
      out.write("      <!-- Repeat to ensure smooth scroll -->\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./animal.jpeg\" alt=\"Animal\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./Tu_Jhoothi_Main_Makkaar_poster.jpeg\" alt=\"TJMM\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./barfi.jpeg\" alt=\"Barfi\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./Sanju.jpeg\" alt=\"Sanju\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./ye_jawani_hai_diwani.jpeg\" alt=\"YJHD\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./rockstar.jpeg\" alt=\"Rockstar\"></div>\n");
      out.write("      <div class=\"vertical-slide\"><img src=\"./Brahmastra_Part_One.jpeg\" alt=\"Brahmastra\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
