/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-07-15 10:31:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class upcoming_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>MovieZone - Premium UI</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    * {\n");
      out.write("      box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    body {\n");
      out.write("      font-family: 'Poppins', sans-serif;\n");
      out.write("      background: #0f2027;\n");
      out.write("      color: white;\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      min-height: 100vh;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /* 🎞 Upcoming Movies (static layout) */\n");
      out.write("    .horizontal-slider-section {\n");
      out.write("      background: rgba(255, 255, 255, 0.05);\n");
      out.write("      padding: 20px 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .horizontal-slider-section h2 {\n");
      out.write("      text-align: center;\n");
      out.write("      font-size: 1.4rem;\n");
      out.write("      color: #00ffcc;\n");
      out.write("      margin-bottom: 14px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("  .horizontal-slider-static {\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: center;\n");
      out.write("  gap: 60px; /* increased spacing */\n");
      out.write("  flex-wrap: wrap;\n");
      out.write("  padding: 10px 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-slide {\n");
      out.write("  width: 200px; /* wider images */\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-slide img {\n");
      out.write("  width: 200px;\n");
      out.write("  height: 280px;\n");
      out.write("  border-radius: 14px;\n");
      out.write("  object-fit: cover;\n");
      out.write("  transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("  box-shadow: 0 0 16px rgba(0, 255, 204, 0.3);\n");
      out.write("}\n");
      out.write("\n");
      out.write("    .movie-slide img:hover {\n");
      out.write("      transform: scale(1.05);\n");
      out.write("      box-shadow: 0 0 22px rgba(0, 255, 204, 0.6);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .hover-caption {\n");
      out.write("      margin-top: 6px;\n");
      out.write("      font-size: 0.9rem;\n");
      out.write("      color: #00ffcc;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    h2 {\n");
      out.write("      text-align: center;\n");
      out.write("      margin: 16px 0 6px;\n");
      out.write("      font-size: 1.4rem;\n");
      out.write("      color: #00ffcc;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .now-showing-section {\n");
      out.write("      padding: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-container {\n");
      out.write("      display: flex;\n");
      out.write("      flex-wrap: wrap;\n");
      out.write("      justify-content: center;\n");
      out.write("      gap: 30px;\n");
      out.write("      padding: 10px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-card {\n");
      out.write("      background: rgba(255, 255, 255, 0.1);\n");
      out.write("      border-radius: 18px;\n");
      out.write("      width: 300px;\n");
      out.write("      box-shadow: 0 6px 16px rgba(0, 0, 0, 0.5);\n");
      out.write("      text-align: center;\n");
      out.write("      overflow: hidden;\n");
      out.write("      transition: transform 0.3s ease;\n");
      out.write("      position: relative;\n");
      out.write("      backdrop-filter: blur(8px);\n");
      out.write("      -webkit-backdrop-filter: blur(8px);\n");
      out.write("      border: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-card:hover {\n");
      out.write("      transform: translateY(-8px) scale(1.04);\n");
      out.write("      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.6);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-card img {\n");
      out.write("      width: 100%;\n");
      out.write("      height: 340px;\n");
      out.write("      object-fit: cover;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-card h3 {\n");
      out.write("      margin: 10px 0 5px;\n");
      out.write("      font-size: 1.2rem;\n");
      out.write("      color: #00ffcc;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .genre-badge, .rating-badge {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 12px;\n");
      out.write("      padding: 4px 10px;\n");
      out.write("      background: #00ffcc;\n");
      out.write("      color: #000;\n");
      out.write("      border-radius: 6px;\n");
      out.write("      font-size: 0.75rem;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .genre-badge {\n");
      out.write("      left: 12px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .rating-badge {\n");
      out.write("      right: 12px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-card a {\n");
      out.write("      display: inline-block;\n");
      out.write("      margin: 10px auto 16px;\n");
      out.write("      padding: 10px 20px;\n");
      out.write("      background-color: #00ffcc;\n");
      out.write("      color: #000;\n");
      out.write("      text-decoration: none;\n");
      out.write("      border-radius: 8px;\n");
      out.write("      font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .movie-card a:hover {\n");
      out.write("      background-color: #00ccb3;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write(" <!-- 🎞 Upcoming Movies Section -->\n");
      out.write("<div class=\"horizontal-slider-section\">\n");
      out.write("  <h2>🎞 Upcoming Movies</h2>\n");
      out.write("  <div class=\"horizontal-slider-static\">\n");
      out.write("    <div class=\"movie-slide\">\n");
      out.write("      <img src=\"./war2.jpeg\" alt=\"War 2\">\n");
      out.write("      <div class=\"hover-caption\">War 2</div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"movie-slide\">\n");
      out.write("      <img src=\"./rajasaheb.jpeg\" alt=\"Rajasaheb\">\n");
      out.write("      <div class=\"hover-caption\">Rajasaheb</div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"movie-slide\">\n");
      out.write("      <img src=\"./superman.jpeg\" alt=\"Superman\">\n");
      out.write("      <div class=\"hover-caption\">Superman</div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"movie-slide\">\n");
      out.write("      <img src=\"./mufasa.jpeg\" alt=\"Mufasa\">\n");
      out.write("      <div class=\"hover-caption\">Mufasa</div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("  <!-- 🍿 Now Showing Section -->\n");
      out.write("  <div class=\"now-showing-section\">\n");
      out.write("    <h2>Now Showing</h2>\n");
      out.write("    <div class=\"movie-container\">\n");
      out.write("      <div class=\"movie-card\">\n");
      out.write("        <img src=\"./brahmastra.jpeg\" alt=\"Brahmastra\">\n");
      out.write("        <div class=\"genre-badge\">Mythology</div>\n");
      out.write("        <div class=\"rating-badge\">4.5⭐</div>\n");
      out.write("        <h3>Brahmastra Part-2</h3>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookmovie.jsp?movie=Brahmastra Part-2\">Book</a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"movie-card\">\n");
      out.write("        <img src=\"./ramayana.jpeg\" alt=\"Ramayana\">\n");
      out.write("        <div class=\"genre-badge\">Mythology</div>\n");
      out.write("        <div class=\"rating-badge\">4.7⭐</div>\n");
      out.write("        <h3>Ramayana</h3>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookmovie.jsp?movie=Ramayana\">Book</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
